### PR TITLE
setting up basics (beyond existing draft PR)

### PR DESCRIPTION
**Pull request by egonzalezg9**
Added dayjs to the dependencies so it would work for anyone testing it out once the draft PR is merged. 
Set up shell for the modules (page/widget). I followed structure in Apostrophe but let me know if it should be different

### CODE REVIEW

**Comment by egonzalezg9** [comment]
@abea @boutell How should I handle my own PRs on this one? I haven't wanted to merge it just to make sure it got another pair of eyes, if that's the process to follow.

**Comment by abea** [comment]
@egonzalezg9 You can request a review from me

**Comment by boutell** [comment]
Sorry, is this  meant to build on top of @bulldoguk's PR? If so should it be rebased on top of that one? Or is it a separate porting attempt? Hopefully you can work together to get to a complete solution more quickly, if I'm not misunderstanding the situation.

**Comment by boutell** [comment]
OK this looks like just the bare beginning — should it be closed in favor of the other PR?

**Comment by egonzalezg9** [comment]
Hi @boutell yes it's meant to build on top of @bulldoguk PR. I didn't want to clutter that one with a smaller addition since there's a lot of commentary going on in it. Would it be worth merging the other PR as it stands now and then contribute from there?

**Comment by boutell** [comment]
Hi @egonzalezg9, I am going to close this PR for now, but feel free to open PRs against Bulldog's if it hasn't merged yet by the time you're ready. There's been a lot of evolution over there.

**Pull request closed without merging**
